### ISSUE TITLE
page still killed on infinite loop

### ISSUE THREAD

**Issue by vjsevill** [kennethtruong/pagrader#32]
Hey Kenneth, looks like the infinite loop associated with the PA2 for cs5fer was resolved.  However, the infinite loop with the PA2 for cs5ffa is still resulting in an unresponsive page.  Thanks by the way.

**Comment by kennethtruong** [comment]
Woops! I was manually updating the PAs for PA2 I must have missed cs5ffa (I didn't thoroughly check your assignments because I thought only cs5fer was the only infinite loop). I didn't want to re-run the updated script for this assignment but it should be good for the future assignments.
